Update java-ci-cd.yml

diff --git a/.github/workflows/java-ci-cd.yml b/.github/workflows/java-ci-cd.yml
--- a/.github/workflows/java-ci-cd.yml
+++ b/.github/workflows/java-ci-cd.yml
@@ -61,8 +61,13 @@ jobs:
            LATEST_TAG=$(aws ecr describe-images --repository-name $ECR_REPO \
            --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' \
            --output text 2>/dev/null)
-            echo "LATEST_TAG output: $LATEST_TAG"
-            if [[ -z "$LATEST_TAG" ]]; then
+           echo "LATEST_TAG output: $LATEST_TAG"
+           
+           if [[ "$LATEST_TAG" == *"An error occurred"* ]]; then
+            echo "Error: AWS CLI command failed: $LATEST_TAG"
+            exit 1
+           fi
+            if [[ -z "$LATEST_TAG" || "$LATEST_TAG" == "None" || "$LATEST_TAG" == "null" ]]; then
               NEW_TAG="v1"
             else
               VERSION_NUM=$(echo "$LATEST_TAG" | grep -oE '[0-9]+$')
@@ -76,7 +81,6 @@ jobs:
             echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
             echo "Latest tag: $LATEST_TAG"
             echo "New tag: $NEW_TAG"
-
             docker build -t "$ECR_REPO:$NEW_TAG" . 
             docker push "$ECR_REPO:$NEW_TAG" 
             echo "image=$ECR_REPO:$NEW_TAG" >> $GITHUB_OUTPUT
